$AzureUserName="AzureUserNameValue"
$AzurePassword="AzurePasswordValue"
$AzureTenantID="AzureTenantIDValue"
$AzureSubscriptionID="AzureSubscriptionIDValue"
$DeploymentID="DeploymentIDValue"
$AdminUsername="AdminUsernameValue"
$AdminPassword="AdminPasswordValue"
